'''
Recursive_Linked_List_Addition.py implements linked-list addition using a recursive digit-by-digit strategy, 
treating missing digits as 0, propagating the carry between recursive calls, and constructing the resulting 
sum linked list as the recursion progresses. 🔗➕🔄
'''

from typing     import Optional
from ListNode   import ListNode

class Recursive_LL_Add:
    """
    🔗 Implements linked-list addition using recursion.

    Each recursive call processes one digit from both operands,
    propagates the carry to the next position, and appends the
    resulting digit to the answer list.

    The recursion stops only when:
        1️⃣ Both operands are exhausted.
        2️⃣ No carry remains.
    """

    def __init__(
        self                    ,
        l1: Optional[ListNode]  ,
        l2: Optional[ListNode]  ,
    ) -> None:

        # 📥 Store references to the two numbers being added.
        self.operand1: Optional[ListNode] = l1
        self.operand2: Optional[ListNode] = l2

        # 🏗️ Pointers used to construct the resulting linked list.
        #
        # sum_head → First node of the result.
        # sum_tail → Last node where the next digit is appended.
        self.sum_head: Optional[ListNode] = None
        self.sum_tail: Optional[ListNode] = None

        # 🎒 Carry generated by the current digit addition.
        # This value is passed into the next recursive call.
        self.carry: int = 0

    def add(self) -> Optional[ListNode]:
        """
        ➕ Recursively adds the two linked-list numbers.

        Returns:
            Optional[ListNode]: Head of the resulting sum linked list.
        """

        # 🛑 BASE CASE
        #
        # When both linked lists are completely processed and there
        # is no carry left, there is nothing more to add.
        #
        # Example:
        #     123 + 456
        #
        # Once every digit has been processed and carry == 0,
        # recursion can safely stop.
        if not self.operand1 and not self.operand2 and not self.carry:
            return None

        # 🧮 Extract the current digits.
        #
        # If one operand has already reached the end, its missing
        # digit is treated as 0.
        #
        # Example:
        #
        #     l1 = [2,4,3]
        #     l2 = [5,6]
        #
        # When l2 is exhausted:
        #
        #     3 + 0 + carry
        node_sum: int = (
                (self.operand1.val if self.operand1 else 0  )
            +   (self.operand2.val if self.operand2 else 0  )
            +   (self.carry                                 )
        )

        # 🔢 The remainder represents the digit that belongs at
        # the current position in the result.
        new_node: Optional[ListNode] = ListNode(node_sum % 10)

        # 🎒 The quotient becomes the carry for the next
        # recursive digit.
        #
        # Example:
        #     17 → digit = 7, carry = 1
        self.carry = node_sum // 10

        # 🌱 Initialize the result list when creating its first node.
        if not self.sum_head:
            self.sum_head = new_node
            self.sum_tail = new_node

        # 🔗 Otherwise, append the newly calculated digit to
        # the end of the result list.
        else:
            self.sum_tail.next  = new_node
            self.sum_tail       = self.sum_tail.next

        # 👉 Move both operands to their next digits.
        #
        # The conditional checks prevent accessing `.next` when
        # an operand has already been completely consumed.
        self.operand1 = (self.operand1.next if self.operand1 else self.operand1)
        self.operand2 = (self.operand2.next if self.operand2 else self.operand2)

        # 🔄 Recursively process the next pair of digits.
        #
        # The updated carry and operand pointers are maintained
        # as object state, so the next call continues exactly
        # where the current call stopped.
        self.add()

        # 🏁 Every recursive call ultimately returns the same
        # result-list head to the original caller.
        return self.sum_head