'''
Single_Pass_Linked_List_Addition.py implements linked-list addition using a single-pass traversal, 
treating missing digits as 0 and processing the carry within the same loop, 
allowing different-length lists and a final carry to be handled cleanly in one unified process. 🔗➕🚀
'''

from typing     import Optional
from ListNode   import ListNode

class Single_Pass_LL_Add:
    """
    🔗 Implements linked-list addition using a single-pass strategy.

    Both linked lists are traversed together in one loop. If either
    operand runs out of digits, its missing digit is treated as 0.

    The loop continues until:
        1️⃣ Both linked lists are completely processed.
        2️⃣ No carry remains.

    This allows numbers of different lengths and a final carry to be
    handled naturally within the same traversal.
    """

    def __init__(
        self,
        l1: Optional[ListNode],
        l2: Optional[ListNode],
    ) -> None:

        # 📥 Keep track of the two numbers we are about to add.
        self.operand1: Optional[ListNode] = l1
        self.operand2: Optional[ListNode] = l2

        # 🎒 Stores the carry generated by the previous digit addition.
        #
        # Example:
        #     8 + 7 = 15
        #
        #     Current digit → 5
        #     Carry         → 1
        self.carry: int = 0

        # 🏗️ Pointers used to construct the resulting linked list.
        #
        # sum_head → First node of the answer.
        # sum_tail → Last node, where the next digit is attached.
        self.sum_head: Optional[ListNode] = None
        self.sum_tail: Optional[ListNode] = None

    def add(self) -> Optional[ListNode]:
        """
        ➕ Adds the two numbers represented by the linked lists.

        Returns:
            Optional[ListNode]: Head of the resulting sum linked list.
        """

        # 🚪 If one operand is missing, there is nothing to add to it.
        #    Return the other list directly.
        if not self.operand1: return self.operand2
        if not self.operand2: return self.operand1

        # 🔄 Reset the result state before starting the addition.
        self.sum_head   = None
        self.sum_tail   = None
        self.carry      = 0

        # ==========================================================
        # 🚀 SINGLE-PASS ADDITION
        # ==========================================================
        #
        # Continue while:
        #
        #   🔵 operand1 still has digits
        #   🟢 operand2 still has digits
        #   🟡 OR a carry still needs to be processed
        #
        # The final condition is important!
        #
        # Example:
        #     9 + 1 = 10
        #
        # After processing both nodes, a carry of 1 remains.
        # The loop must run one more time to place that carry into
        # the resulting linked list.
        while self.operand1 or self.operand2 or self.carry:

            # 🔢 Extract the current digit from each operand.
            #
            # If one list has already ended, treat its missing digit
            # as 0. This eliminates the need for separate loops for
            # unequal-length linked lists.
            #
            # Example:
            #
            #     l1 = [2,4,3]
            #     l2 = [5,6]
            #
            # On the final digit:
            #
            #     3 + 0 + carry
            node_sum: int = (
                    (self.operand1.val if self.operand1 else 0  )
                +   (self.operand2.val if self.operand2 else 0  )
                +   (self.carry                                 )
            )

            # 🔢 Keep only the current digit for the result node.
            #
            # Example:
            #     14 → digit = 4
            #     20 → digit = 0
            new_node: Optional[ListNode] = ListNode(node_sum % 10)

            # 🎒 Pass the carry forward to the next digit.
            #
            # Example:
            #     14 → carry = 1
            #     20 → carry = 2
            self.carry = node_sum // 10

            # 🌱 If this is the first result node, initialize both
            #    the head and tail pointers.
            if not self.sum_head:
                self.sum_head = new_node
                self.sum_tail = new_node

            # 🔗 Otherwise, append the newly calculated digit to the
            #    end of the result list and advance the tail pointer.
            else:
                self.sum_tail.next  = new_node
                self.sum_tail       = new_node

            # 👉 Move operand 1 forward if it still has a node.
            #
            # The check prevents us from accessing `.next` on None
            # when operand 1 is shorter than operand 2.
            if self.operand1: self.operand1 = self.operand1.next

            # 👉 Move operand 2 forward using the same logic.
            if self.operand2: self.operand2 = self.operand2.next

        # 🏁 Every digit and any final carry have now been processed.
        #    Return the head of the newly constructed sum list.
        return self.sum_head